# https://gohugo.io/getting-started/configuration/#configure-server
# ATTENTION: headers must be the same as in netlify.toml
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "no-referrer"
Permissions-Policy = """
    geolocation=(),
    midi=(),
    notifications=(),
    push=(),
    sync-xhr=(),
    microphone=(),
    camera=(),
    magnetometer=(),
    gyroscope=(),
    speaker=(self),
    vibrate=(),
    fullscreen=(self),
    interest-cohort=()
"""
# "style-src unsafe-inline:" Cf https://github.com/letsencrypt/website/issues/950
# "connect-src https://d4twhgtvn0ff5.cloudfront.net/" for stats graphs
# "img-src data: blob:" is for Plotly download feature
# Stripe, abmr.net (PayPal image assets), and Google domains (reCAPTCHA) are for Donorbox
# "form-action" is NOT set, so it allows everything (it doesn't default to default-src). If restricted, It must allow at least www.paypal.com and its redirects
Content-Security-Policy = """
    default-src 'none';
    font-src 'self';
    style-src 'unsafe-inline' 'self';
    script-src 'unsafe-eval' 'unsafe-inline' 'self' data:
        https://donorbox.org
        https://js.stripe.com/v3/
        https://sdks.shopifycdn.com
    ;
    img-src 'self' data: blob:
        https://www.paypal.com
        https://www.paypalobjects.com
        https://ak2s.abmr.net
        https://ak1s.abmr.net
        https://www.google.com/recaptcha/
        https://www.gstatic.com/recaptcha/
        https://cdn.shopify.com
        https://v.shopify.com
    ;
    frame-src
        https://donorbox.org
        https://js.stripe.com/v3/
        https://js.stripe.com/v2/
    ;
    connect-src 'self'
        https://d4twhgtvn0ff5.cloudfront.net/
        https://letsencrypt-merch.myshopify.com
        https://monorail-edge.shopifysvc.com
    ;
"""

[[headers]]
for = "/repository"
[headers.values]
# For WebTrust Audits
# Cf https://github.com/letsencrypt/website/pull/976
Referrer-Policy = "strict-origin"

[[headers]]
for = "/:lang/repository"
[headers.values]
# For WebTrust Audits
# Cf https://github.com/letsencrypt/website/pull/976
Referrer-Policy = "strict-origin"

[[headers]]
for = "/certs/*.pem"
[headers.values]
# Because Netlify defaults to "application/x-x509-ca-cert", which is for DER.
Content-Type = "application/x-pem-file"
Content-Disposition = "inline"
